apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: do-token
  namespace: core
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gitlab-secrets
    kind: SecretStore
  target:
    name: do-token
  dataFrom:
  - extract:
      key: do_token
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: pyapi
  namespace: apps
  labels:
    app.kubernetes.io/name: pyapi
    app.kubernetes.io/instance: pyapi
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gitlab-secrets
    kind: SecretStore
  target:
    name: pyapi
  dataFrom:
  - key: pyapi
