apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gitlab-secrets
  namespace: apps
spec:
  provider:
    gitlab:
      auth:
        SecretRef:
          accessToken:
            name: gitlab-secret
            key: token
      projectID: "33440703"
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gitlab-secrets
  namespace: core
spec:
  provider:
    gitlab:
      auth:
        SecretRef:
          accessToken:
            name: gitlab-secret
            key: token
      projectID: "33440703"
