apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: core
spec:
  interval: 10m0s
  chart:
    spec:
      version: 4.2.5
      chart: ingress-nginx
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    controller:
      service:
        ports:
          http: 80
          https: 443
        targetPorts:
          http: http
          https: http
        annotations:
          external-dns.alpha.kubernetes.io/hostname: ndsquared.net
          service.beta.kubernetes.io/do-loadbalancer-name: "ndsq-prod-sfo3-lb"
          # service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
          # service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
          # service.beta.kubernetes.io/do-loadbalancer-tls-passthrough: "true"
          # service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
          service.beta.kubernetes.io/do-loadbalancer-certificate-id: "90f5bdb8-88cd-4a13-962b-6d17b7ea9a7b"
          # service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"
