apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: external-secrets-crs
  namespace: flux-system
spec:
  dependsOn:
    - name: external-secrets
      namespace: flux-system
  interval: 1m
  path: ./kustomizations/external_secrets_crs/overlays/local
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-management
    namespace: flux-system
