apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fake
  namespace: core
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: fake
    kind: ClusterSecretStore
  target:
    name: do-token
  dataFrom:
  - extract:
      key: do-token
