apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: fake
spec:
  provider:
    fake:
      data:
      - key: "do-token"
        valueMap:
          digitalocean_api_token: notarealtoken
