apiVersion: v1
kind: ConfigMap
metadata:
  name: portfolio
  labels:
    app.kubernetes.io/name: portfolio
    app.kubernetes.io/instance: portfolio
data:
  PYAPI_BASE_URL: https://pyapi.ndsquared.net
  GOAPI_BASE_URL: https://goapi.ndsquared.net
